server:
  port: 2000
spring:
  application:
    name: atguigu-crowd-mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/project-crowd?serverTimezone=UTC
    username: root
    password: 13313288898lzt
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
logging:
  level:
    com.lzt.crowd.mapper: debug
    com.lzt.crowd.test: debug
